/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bars: typeof import('./../src/components/playbar/bars.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    Gaogao: typeof import('./../src/components/gaogao.vue')['default']
    Playbar: typeof import('./../src/components/playbar/index.vue')['default']
    PlayBar: typeof import('./../src/components/playbar/playBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunHouse: typeof import('./../src/components/playbar/runHouse.vue')['default']
    TimeText: typeof import('./../src/components/playbar/timeText.vue')['default']
  }
}
